config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :opps
  resources :opps do
    member do
      post :add_progress
    end
  end
  # get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/opp.rb
class Opp < ApplicationRecord
    belongs_to :user
    serialize :progress, coder: YAML, type: Array

    after_initialize do |b|
        b.progress = [] if b.progress == nil
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        has_many :opps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
      opps_path(current_user) # your path
    end
    def after_sign_out_path_for(resource_or_scope)
      new_user_session_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/opps_controller.rb
class OppsController < ApplicationController
  before_action :set_opp, only: %i[ show edit update destroy ]

  # GET /opps or /opps.json
  def index
      @opps = Opp.where(:user_id => current_user)
  end

  # GET /opps/1 or /opps/1.json
  def show
      @opps = Opp.find(params[:id])
  end

  # GET /opps/new
  def new
    @opp = Opp.new
  end

  # GET /opps/1/edit
  def edit
  end

  # POST /opps or /opps.json
  def create
    @opp = Opp.new(opp_params)

    respond_to do |format|
      if @opp.save
        format.html { redirect_to opp_url(@opp), notice: "Opp was successfully created." }
        format.json { render :show, status: :created, location: @opp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @opp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opps/1 or /opps/1.json
  def update
    new_value = params[:opp][:new_progress] # Assuming the name of the field in the form is 'new_value'
    updated_array = @opp.progress.append(new_value) if new_value.present?

    respond_to do |format|
      if @opp.update(opp_params)
        format.html { redirect_to opp_url(@opp), notice: "Opp was successfully updated." }
        format.json { render :show, status: :ok, location: @opp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @opp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opps/1 or /opps/1.json
  def destroy
    @opp.destroy!

    respond_to do |format|
      format.html { redirect_to opps_url, notice: "Opp was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opp
      @opp = Opp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def opp_params
      params.require(:opp).permit(:name,:contact_info, :opp_reason, :progress, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opps_helper.rb
module OppsHelper
end

app/views/home/about.html.erb
<div class="bg-white h-full">
  <div class="mx-auto grid max-w-2xl grid-cols-1 items-center gap-x-8 gap-y-16 px-4 py-24 sm:px-6 sm:py-32 lg:max-w-7xl lg:px-8">
    <div>
      <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">About Blicky.</h2>
      <p class="mt-4 text-gray-500">Blicky reimagines CRM systems for tracking enemies, offering a unique platform to catalog rivals' details, behaviors, and vulnerabilities. It provides analytical tools and a secure database for strategic advantage in competitive scenarios, making it an essential tool for anyone looking to systematically understand and outmaneuver their adversaries.</p>

      <dl class="mt-16 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 sm:gap-y-16 lg:gap-x-8">
        <div class="border-t border-gray-200 pt-4">
          <dt class="font-medium text-gray-900">Peaceful Origins</dt>
          <dd class="mt-2 text-sm text-gray-500">Meant to stop the bullies in their tracks</dd>
        </div>
        <div class="border-t border-gray-200 pt-4">
          <dt class="font-medium text-gray-900">Battle-Tested Technology</dt>
          <dd class="mt-2 text-sm text-gray-500">Built on the bulletproof web framework crafted by DHH himself</dd>
        </div>
        <div class="border-t border-gray-200 pt-4">
          <dt class="font-medium text-gray-900">All Areas</dt>
          <dd class="mt-2 text-sm text-gray-500">We're kindly serving individuals in all areas and locations</dd>
        </div>
        <div class="border-t border-gray-200 pt-4">
          <dt class="font-medium text-gray-900">Progress Tracking</dt>
          <dd class="mt-2 text-sm text-gray-500">Are they still your opp? Maybe they've had a change of heart</dd>
        </div>
        <div class="border-t border-gray-200 pt-4">
          <dt class="font-medium text-gray-900">Includes</dt>
          <dd class="mt-2 text-sm text-gray-500">Nothing really. It's meant to be simple but good</dd>
        </div>
        <div class="border-t border-gray-200 pt-4">
          <dt class="font-medium text-gray-900">Considerations</dt>
          <dd class="mt-2 text-sm text-gray-500">We're very considerate of your feelings and one day we might ask for your feedback!</dd>
        </div>
      </dl>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="bg-white h-full">
  <div class="relative isolate px-6 pt-8 lg:px-8">
    <div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" aria-hidden="true">
      <div class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
    <div class="mx-auto max-w-2xl py-32">
      <div class="hidden sm:mb-8 sm:flex sm:justify-center">
        <div class="relative rounded-full px-3 py-1 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">
          Learn about our mission
          <%= link_to "Learn more →", home_about_path, class:"text-sm font-semibold leading-6 text-gray-900" %>
        </div>
      </div>
      <div class="text-center">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">All Your Opps Organized Into One Place.</h1>
        <p class="mt-6 text-lg leading-8 text-gray-600">Dude don't think too hard about it. It's a CRM but for all your opps. Opps as in anyone that threatens you, pulls up on you, or even looks at you weird. They all go in here.</p>
        <div class="mt-10 flex items-center justify-center gap-x-6">
            <%= link_to "Get Started", new_user_session_path, class:"rounded-md bg-black px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-gray-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
          <%= link_to "Learn more →", home_about_path, class:"text-sm font-semibold leading-6 text-gray-900" %>
        </div>
      </div>
    </div>
    <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]" aria-hidden="true">
      <div class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>Blicky CRM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen w-full flex flex-col">
      <p class="notice text-center"><%= notice %></p>
      <p class="alert text-center"><%= alert %></p>
    <header class="w-full z-10">
        <nav class="bg-black">
          <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            <div class="relative flex h-16 items-center justify-between">
              <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
                <!-- Mobile menu button-->
                <button type="button" onclick="openMenu()" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
                  <span class="absolute -inset-0.5"></span>
                  <span class="sr-only">Open main menu</span>
                  <!--
                    Icon when menu is closed.

                    Menu open: "hidden", Menu closed: "block"
                  -->
                  <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                  </svg>
                  <!--
                    Icon when menu is open.

                    Menu open: "block", Menu closed: "hidden"
                  -->
                  <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
              <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
                <div class="flex flex-shrink-0 items-center">
                  <!-- <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company"> -->
                  <a href="/">
                  <h2 class="font-black text-2xl text-white">blicky.</h2>
                  </a>
                </div>
                <div class="hidden sm:ml-6 sm:block">
                  <div class="flex space-x-4">
                    <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                    <% if user_signed_in?%>
                        <%= link_to "Dashboard", opps_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
                        <%= link_to "Profile", edit_user_registration_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
                        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
                    <% else %>
                        <%= link_to "About", home_about_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
                        <%= link_to "Sign In", new_user_session_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
              </div>
            </div>
          </div>

          <!-- Mobile menu, show/hide based on menu state. -->
          <div class="sm:hidden hidden" id="mobile-menu">
            <div class="space-y-1 px-2 pb-3 pt-2 flex flex-col md:flex-row">
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <% if user_signed_in?%>
                  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"hidden sm:block text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
                  <%= link_to "Edit Profile", edit_user_registration_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
                  <%= link_to "Opps", opps_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
                  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"block sm:hidden text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
              <% else %>
                  <%= link_to "About", home_about_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
                  <%= link_to "Sign In", new_user_session_path, class:"text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" %>
              <% end %>
            </div>
            </div>
          </div>
        </nav>
    </header>

    <main class="flex w-full h-full items-center justify-center">
      <%= yield %>
    </main>
    <script>
        function openMenu(){
          let mobi = document.getElementById("mobile-menu")
          console.log("it's hitting the menu")
          if (mobi.classList.contains('hidden')){
            mobi.classList.remove('hidden');
          }else{
            mobi.classList.add('hidden');
          }

        }
    </script>
  </body>
</html>

app/views/opps/_form.html.erb
<%= form_with(model: opp, class: "contents") do |form| %>
  <% if opp.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(opp.errors.count, "error") %> prohibited this opp from being saved:</h2>

      <ul>
        <% opp.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">

    <%= form.label :contact_info %>
    <%= form.text_field :contact_info, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :opp_reason %>
    <%= form.text_area :opp_reason, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.number_field :user_id, id: :friend_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-black text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/opps/_opp.html.erb
<tr id="<%= dom_id opp %>" class="border-y-2 border-solid border-gray-300 h-[50px]">
    <td>
        <%= link_to opp.name, opp, class: "hover:underline" %>
    </td>

    <td>
        <%= opp.contact_info %>
    </td>

    <td class="hidden sm:table-cell">
        <%= truncate(opp.opp_reason, length: 50) %>
    </td>

  <% if action_name != "show" %>
      <td class="hidden sm:table-cell">
        <%= link_to "Edit", edit_opp_path(opp) %>
    </td>
  <% end %>
</tr>

app/views/opps/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing opp</h1>

  <%= render "form", opp: @opp %>

  <%= link_to "Show this opp", @opp, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to opps", opps_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/opps/index.html.erb
<div class="w-full h-full p-5">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center pb-4">
    <h1 class="font-bold text-4xl">Dashboard</h1>
    <%= link_to "Add +", new_opp_path, class: "rounded-lg py-3 px-5 bg-black text-white block font-medium" %>
  </div>

  <div id="opps" class="min-w-full">
  <table class="w-full">
      <tr>
          <th class="font-bold text-left text-xl">
              Name
          </th>
          <th class="font-bold text-left text-xl">
              Contact Info
          </th>
          <th class="font-bold text-left text-xl hidden sm:table-cell">
              Opping Reason
          </th>
          <th class="font-bold text-left text-xl hidden sm:table-cell">
              Options
          </th>
      </tr>
    <%= render @opps %>
  </table>
  </div>
</div>

app/views/opps/new.html.erb
<div class="m-4 md:mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">Add New Opp</h1>

  <%= render "form", opp: @opp %>

  <%= link_to "Back to opps", opps_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/opps/show.html.erb
<div class="m-3 md:mx-auto w-full">
  <div class="mx-auto md:w-1/3 flex flex-col gap-5">
    <% if notice.present? %>
      <!-- <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p> -->
    <% end %>
    <h2 class="text-3xl font-bold"><%= @opp.name %>'s Profile</h2>
    <div>
    <h2 class="font-bold">Opp Contact:</h2>
    <p>
        <%= @opp.contact_info %>
    </p>
    </div>

    <div>
    <h2 class="font-bold">Reason for Opping:</h2>
    <p>
        <%= @opp.opp_reason %>
    </p>
    </div>



    <div>
    <h2 class="font-bold">Progress Updates:</h2>

    <% if @opp.progress.present? %>
      <ul class="list-disc list-inside">
        <% @opp.progress.each do |update| %>
          <li><%= update %></li>
        <% end %>
      </ul>
      <p class="font-bold text-gray-400">
          Last updated @ <%= @opp.updated_at %>
      </p>

    <% else %>
      <p>No progress updates available.</p>
    <% end %>
    </div>

    <%= form_with(model: @opp, class:"flex flex-col gap-2") do |form| %>
        <%= form.label :new_progres, 'New Progress:', class:"font-bold" %>
      <%= form.text_field :new_progress %>

      <%= form.submit "Log Progress", class:"bg-black p-2 rounded-md text-white" %>
    <% end %>

    <div class="flex flex-row justify-evenly gap-2">
    <%= link_to "Edit", edit_opp_path(@opp), class: "rounded-lg py-3 w-full bg-gray-100 inline-block font-medium text-center" %>
    <div class="inline-block w-full">
      <%= button_to "Delete", opp_path(@opp), method: :delete, class: "rounded-lg py-3 w-full bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back", opps_path, class: "rounded-lg py-3 w-full bg-gray-100 inline-block font-medium text-center" %>
    </div>
  </div>
</div>